"""Add detection details to ProcessingResult

Revision ID: a95b01f834be
Revises: 2beb8c2faeb5
Create Date: 2026-10-07 23:14:44.779185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a95b01f834be'
down_revision: Union[str, Sequence[str], None] = '2beb8c2faeb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_results', sa.Column('detection_score', sa.Integer(), nullable=True))
    op.add_column('processing_results', sa.Column('matched_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processing_results', 'matched_signals')
    op.drop_column('processing_results', 'detection_score')
    # ### end Alembic commands ###
